import Web3 from 'web3';
import { Utils } from './Utils';

// Types
import { Provider } from '@0xproject/types';
import { ECSignature, Order, SignedOrder } from '../types/Order';
import { ITxParams, MarketContract, OrderLib } from '@marketprotocol/types';
import { BigNumber } from 'bignumber.js';

/**
 * Computes the orderHash for a supplied order.
 * @param   provider   Web3 provider instance.
 * @param   orderLibAddress address of the deployed OrderLib.sol
 * @param   order      An object that confirms to the Order interface definitions.
 * @return  The resulting orderHash from hashing the supplied order.
 */
export async function createOrderHashAsync(
  provider: Provider,
  orderLibAddress: string,
  order: Order | SignedOrder
): Promise<string> {
  // below assert statement fails due to issues with BigNumber vs Number.
  // assert.isSchemaValid('Order', order, schemas.OrderSchema);

  const web3: Web3 = new Web3();
  web3.setProvider(provider);

  const orderLib: OrderLib = await OrderLib.createAndValidate(web3, orderLibAddress);

  return orderLib
    .createOrderHash(
      order.contractAddress,
      // orderAddresses
      [order.maker, order.taker, order.feeRecipient],
      // unsignedOrderValues
      [order.makerFee, order.takerFee, order.price, order.expirationTimestamp, order.salt],
      order.orderQty
    )
    .then(data => data)
    .catch((err: Error) => {
      const error = 'Error while creating order hash';
      console.error(err);
      return error;
    });
}

/***
 * Creates and signs a new order given the arguments provided
 * @param {Provider} provider               Web3 provider instance.
 * @param {string} orderLibAddress          address of the deployed OrderLib.sol
 * @param {string} contractAddress          address of the deployed MarketContract.sol
 * @param {BigNumber} expirationTimestamp   unix timestamp
 * @param {string} feeRecipient             address of account to receive fees
 * @param {string} maker                    address of maker account
 * @param {BigNumber} makerFee              fee amount for maker to pay
 * @param {string} taker                    address of taker account
 * @param {BigNumber} takerFee              fee amount for taker to pay
 * @param {BigNumber} orderQty              qty of Order
 * @param {BigNumber} price                 price of Order
 * @param {BigNumber} remainingQty          qty remaining
 * @param {BigNumber} salt                  used to ensure unique order hashes
 * @return {Promise<SignedOrder>}
 */
export async function createSignedOrderAsync(
  provider: Provider,
  orderLibAddress: string,
  contractAddress: string,
  expirationTimestamp: BigNumber,
  feeRecipient: string,
  maker: string,
  makerFee: BigNumber,
  taker: string,
  takerFee: BigNumber,
  orderQty: BigNumber,
  price: BigNumber,
  remainingQty: BigNumber,
  salt: BigNumber
): Promise<SignedOrder> {
  const order: Order = {
    contractAddress: contractAddress,
    expirationTimestamp: expirationTimestamp, // '', makerAccount, 0, 1, 100000, 1, '', 0
    feeRecipient: feeRecipient,
    maker: maker,
    makerFee: makerFee,
    orderQty: orderQty,
    price: price,
    remainingQty: remainingQty,
    salt: salt,
    taker: taker,
    takerFee: takerFee
  };

  const orderHash: string | BigNumber = await createOrderHashAsync(
    provider,
    orderLibAddress,
    order
  );

  const signedOrder: SignedOrder = {
    contractAddress: contractAddress,
    expirationTimestamp: expirationTimestamp,
    feeRecipient: feeRecipient,
    maker: maker,
    makerFee: makerFee,
    orderQty: orderQty,
    price: price,
    remainingQty: remainingQty,
    salt: salt,
    taker: taker,
    takerFee: takerFee,
    ecSignature: await signOrderHashAsync(provider, String(orderHash), maker)
  };

  return signedOrder;
}

/**
 * Confirms a signed order is validly signed
 * @param provider
 * @param orderLibAddress
 * @param signedOrder
 * @param orderHash
 * @return boolean if order hash and signature resolve to maker address (signer)
 */
export async function isValidSignatureAsync(
  provider: Provider,
  orderLibAddress: string,
  signedOrder: SignedOrder,
  orderHash: string
): Promise<boolean> {
  const web3: Web3 = new Web3();
  web3.setProvider(provider);
  const orderLib: OrderLib = await OrderLib.createAndValidate(web3, orderLibAddress);
  return orderLib.isValidSignature(
    signedOrder.maker,
    orderHash,
    signedOrder.ecSignature.v,
    signedOrder.ecSignature.r,
    signedOrder.ecSignature.s
  );
}

/**
 * Signs an orderHash and returns it's elliptic curve signature.
 * @param   provider        Web3 provider instance.
 * @param   orderHash       Hex encoded orderHash to sign.
 * @param   signerAddress   The hex encoded Ethereum address you wish to sign it with. This address
 *          must be available via the Provider supplied to MARKET.js.
 * @return  An object containing the Elliptic curve signature parameters generated by signing the orderHash.
 */
export async function signOrderHashAsync(
  provider: Provider,
  orderHash: string,
  signerAddress: string
): Promise<ECSignature> {
  const web3: Web3 = new Web3();
  web3.setProvider(provider);
  return Utils.signMessage(web3, signerAddress, orderHash);
}

/**
 * Trades an order and returns success or error.
 * @param   provider        Web3 provider instance.
 * @param   signedOrder     An object that conforms to the SignedOrder interface. The
 *                          signedOrder you wish to validate.
 * @param   fillQty         The amount of the order that you wish to fill.
 * @param   txParams        Transaction params of web3.
 * @return  A boolean indicating whether the order has been successfully traded or not.
 */
export async function tradeOrderAsync(
  provider: Provider,
  signedOrder: SignedOrder,
  fillQty: BigNumber,
  txParams: ITxParams = {}
): Promise<BigNumber | number> {
  // assert.isSchemaValid('SignedOrder', signedOrder, schemas.SignedOrderSchema);

  const web3: Web3 = new Web3();
  web3.setProvider(provider);

  const marketContract: MarketContract = new MarketContract(web3, signedOrder.contractAddress);

  const txHash: string = await marketContract
    .tradeOrderTx(
      // orderAddresses
      [signedOrder.maker, signedOrder.taker, signedOrder.feeRecipient],
      // unsignedOrderValues
      [
        signedOrder.makerFee,
        signedOrder.takerFee,
        signedOrder.price,
        signedOrder.expirationTimestamp,
        signedOrder.salt
      ],
      signedOrder.orderQty,
      fillQty,
      signedOrder.ecSignature.v,
      signedOrder.ecSignature.r,
      signedOrder.ecSignature.s
    )
    .send(txParams);

  const blockNumber: number = Number(web3.eth.getTransaction(txHash).blockNumber);

  return new Promise<BigNumber | number>((resolve, reject) => {
    const stopEventWatcher = marketContract
      .OrderFilledEvent({ maker: signedOrder.maker })
      .watch({ fromBlock: blockNumber, toBlock: blockNumber }, (err, eventLog) => {
        // Validate this tx hash matches the tx we just created above.
        if (err) {
          console.log(err);
        }

        if (eventLog.transactionHash === txHash) {
          stopEventWatcher()
            .then(function() {
              return resolve(eventLog.args.filledQty);
            })
            .catch(reject);
        }
      });
  });
  // TODO: listen for error events marketContract.ErrorEvent()
}
